# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dialy}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Georg Ledermann"]
  s.date = %q{2011-03-25}
  s.description = %q{Knows all area codes from Germany, Austria and Switzerland}
  s.email = %q{mail@georg-ledermann.de}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dialy.gemspec",
    "lib/dialy.rb",
    "lib/dialy/config.rb",
    "lib/dialy/data.rb",
    "lib/dialy/data/at.rb",
    "lib/dialy/data/ch.rb",
    "lib/dialy/data/countries.rb",
    "lib/dialy/data/de.rb",
    "lib/dialy/formatter.rb",
    "spec/dialy_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ledermann/dialy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Formatting phone numbers in E.123}
  s.test_files = [
    "spec/dialy_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

